drop SCHEMA if exists hw6 CASCADE;
CREATE SCHEMA hw6 AUTHORIZATION "admin";

CREATE TABLE hw6."groups" (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	group_name varchar NOT NULL,
	CONSTRAINT group_pk PRIMARY KEY (id)
);

CREATE TABLE hw6.teachers (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	full_name varchar NOT NULL,
	CONSTRAINT teachers_pk PRIMARY KEY (id)
);

CREATE TABLE hw6.students (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	full_name varchar NOT NULL,
	group_id int NULL,
	CONSTRAINT students_pk PRIMARY KEY (id)
);

ALTER TABLE hw6.students ADD CONSTRAINT students_groups_fk FOREIGN KEY (group_id) REFERENCES hw6."groups"(id);

CREATE TABLE hw6.subjects (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	subject_name varchar NOT NULL,
	teacher_id int NULL,
	CONSTRAINT subjects_pk PRIMARY KEY (id)
);

ALTER TABLE hw6.subjects ADD CONSTRAINT subjects_teachers_fk FOREIGN KEY (teacher_id) REFERENCES hw6.teachers(id);

CREATE TABLE hw6.marks (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	student_id int NOT NULL,
	subject_id int NOT NULL,
	mark int NOT NULL,
	"timestamp" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT marks_pk PRIMARY KEY (id)
);

ALTER TABLE hw6.marks ADD CONSTRAINT marks_students_fk FOREIGN KEY (student_id) REFERENCES hw6.students(id);
ALTER TABLE hw6.marks ADD CONSTRAINT marks_subjects_fk FOREIGN KEY (subject_id) REFERENCES hw6.subjects(id);

COMMIT;